### ISSUE TITLE
Using OpenSSL's 'built in' zip functionality

### ISSUE THREAD

**Issue by PeterMosmans** [splitice/encrypted-email-backup#1]
Nice shell script!
Minor tip: I don't know if you're aware of this, but you could use the built-in compression utility of OpenSSL (if it's compiled with the zlib option). Currently there are several pipes being used

`cat - | gzip | openssl enc -aes-256-cbc -kfile "$BACKUP_KEY" > "$BACKUP_FILE"`

You could replace this by using

`cat - | openssl enc -aes-256-cbc -kfile "$BACKUP_KEY" -z > "$BACKUP_FILE"`

This probably is a bit more efficient, both processor- and space-wise.
Likewise you can use the -z flag for decompression as well:

Replace

`cat - | openssl enc -aes-256-cbc -d -kfile "$BACKUP_KEY" | gzip -d`

by

`cat - | openssl enc -aes-256-cbc -d -kfile "$BACKUP_KEY" -z`

Cheers,

Peter

**Comment by splitice** [comment]
Interesting, that's new to me. I have an update in the pipeline, I'll be sure to include it :)
